/* eslint-disable import/no-duplicates */
/* eslint-disable import/order */
import "@/index.css";

import { AppWrapper } from "./AppWrapper";

import { Metadata } from "next";

import { Catamaran, Quicksand, Rubik } from "next/font/google";

interface Props {
  children: React.ReactNode;
}

export const metadata: Metadata = {
  title: "Karateklubi Nüke",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1",
};

const catamaran = Catamaran({
  variable: "--main-font",
});
const rubik = Rubik({
  variable: "--rubik-font",
});
const quicksand = Quicksand({
  variable: "--quicksand-font",
});

export default function RootLayout({ children }: Props) {
  return (
    <html className={`${catamaran.variable} ${rubik.variable} ${quicksand.variable}`} lang="et">
      {/*
        <head /> will contain the components returned by the nearest parent
        head.tsx. Find out more at https://beta.nextjs.org/docs/api-reference/file-conventions/head
      */}
      <head />
      <body className={catamaran.className}>
        <AppWrapper>{children}</AppWrapper>
      </body>
    </html>
  );
}
