/* eslint-disable import/no-duplicates */
/* eslint-disable import/order */
import "@/index.css";

import { AppWrapper } from "./AppWrapper";

import { Metadata } from "next";

import { Catamaran, Quicksand, Rubik } from "next/font/google";

interface Props {
  children: React.ReactNode;
}

export const metadata: Metadata = {
  title: "Karateklubi Nüke",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1",
  robots: {
    index: true,
  },
};

const catamaran = Catamaran({
  variable: "--main-font",
  subsets: ["latin"],
});
const rubik = Rubik({
  variable: "--rubik-font",
  subsets: ["latin"],
});
const quicksand = Quicksand({
  variable: "--quicksand-font",
  subsets: ["latin"],
});

export default function RootLayout({ children }: Props) {
  return (
    <html className={`${catamaran.variable} ${rubik.variable} ${quicksand.variable}`} lang="et">
      <head />

      <body>
        <AppWrapper>{children}</AppWrapper>
      </body>
    </html>
  );
}
